name: Coveralls

on:
  # pull-request:
  #   branches:
  #     - "*" # Replace with your branch name
  push:
    branches:
      - v2 # Replace with your branch name

jobs:
  coveralls:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1. # Replace with your Go version

      - name: Install 'goveralls'
        run: go install github.com/mattn/goveralls

      - name: Run tests and generate coverage report
        run: |
          go test -v -coverprofile=coverage.out ./...
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

      - name: Upload coverage report to Coveralls
        run: goveralls -coverprofile=coverage.out -service=github
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
